// config.prod.js

// ApiCredentials.js

const ApiCredentials = {
    credentials: {
        apiUrl: "https://testapps.bbmpgov.in/LayoutKhataAPI",
        loginUrl: "https://testapps.bbmpgov.in/testEaasthiAPI/api/values",
        username: "BBMPOTP",
        password: "10750b6bdc29495297efd2fb29047a94",
        layoutForm: "https://testlayoutkhata.bbmpgov.in",
        ekycRequestURL: 1,
        releaseEKYCnamescore: 1,
        totalNoofSites: 5,
    }
};

const config = {
    apiBaseUrl: ApiCredentials.credentials.apiUrl,
    apiLoginBaseUrl: ApiCredentials.credentials.loginUrl,
    redirectBaseURL: ApiCredentials.credentials.layoutForm,
    redirectionTypeURL: ApiCredentials.credentials.ekycRequestURL,
    rd_nameScore: ApiCredentials.credentials.releaseEKYCnamescore,
      sites:  ApiCredentials.credentials.totalNoofSites,

    credentials: ApiCredentials.credentials,
    endpoints: {
        sendOTP: '/fnSendOtp',
        verifyOTP: '/fnValidateOtp',
        epid: '/api/eaasthi/FnGetOwnerKhataDetails',
        send_OTP: '/api/otp/fnSendOtp',
        verify_OTP: '/api/otp/fnValidateOtp',
        kaveriDistrict: '/api/Bhoomi/GetDistrictName',
        kaveriTaluk: '/api/Bhoomi/GetTalukName',
        kaveriHobli: '/api/Bhoomi/GetHobliName',
        kaveriVillage: '/api/Bhoomi/GetVillageName',
        kaveriHissa: '/api/Bhoomi/GetHissaList',
        kaveriFetchDetails: '/api/Bhoomi/GetRTCDetailsWithBhoomiVillage',
        insertApprovalInfo: '/api/Approval/fnInsertApprovalinfo',
        listApprovalInfo: '/api/Approval/fnGetApprovalList',
        deleteApprovalInfo: '/api/Approval/fnDeleteApprovalinfo',
        insertReleaseInfo: '/api/Release/fnInsertReleaseinfo',
        deleteReleaseInfo: '/api/Release/fnDeleteReleaseOrderinfo',
        listReleaseInfo: '/api/Release/fnGetReleaseList',
        fileUpload: '/api/Document/fnUploadDocuments',
        fileUploadList: '/api/Document/fnGetDocumentList',
        insertJDAInfo: '/api/JDA/fnInsertJDAinfo',
        fetchJDAInfo: '/api/JDA/fnGetJDAinfo',
        multipleOwnerfetch: '/api/Owner/fnGetOwnerInfo',
        individualSiteDetails: '/api/Site/fnInsertSiteinfo',
        fetchIndividualSiteDetails: '/api/Site/fnGetSiteInfo',
        fetchECDetails: '/api/Kaveri/FnKaveriGetECDetails',
        fetchDeedDetails: '/api/Kaveri/FnKaveriGetDeedDetails',
        fetchDeedDetailsDoc: '/api/Kaveri/FnKaveriGetDeedDocumentDetails',
        ekyc_request: '/api/EKYC/RequestEKYC',
        ekyc_response: '/api/EKYC/GetEKYCResponse',
        ekyc_ownerInsert: '/api/Owner/fnInsertOwnerinfo',
        delete_siteInfo: '/api/Site/fnDeleteSiteinfo',
        fetchLKRSID: '/api/LKRS/fnGetLKRSInfo',
        layoutKhata_Save: '/api/LKRS/fnSaveLKRSinfo',
        releasePercentage: '/api/Release/fnGetReleasePercentage',
        releaseSites: '/api/Site/fnReleaseSites',
        jdaEKYCOwnerfetch: '/api/JDA/fnGetJDAEkycinfo',
        jdaEKYCInsert: '/api/JDA/fnInsertJDAEkycinfo',
        dashboardcount: '/api/LKRS/fnGetDashCount',
        dashboardData: '/api/LKRS/fnGetDashData',
        releaseEKYCInsert: '/api/Release/fnInsertReleaseEkycinfo',
        fetchZoneWard: '/api/LKRS/fnGetZonefromWardList',
        fetchStreet: '/api/LKRS/fnGetStreetList',
        fetchARO: '/api/LKRS/fnGetARODetails',
        relinquishmentDeed: '/api/LKRS/fnRelinquishmentDeed',
    },
        citizenServicesURL: {
        login: "https://testlayoutkhata.bbmpgov.in/Login",
        getEkhata: "",
        layoutDashboard: "https://testlayoutkhata.bbmpgov.in/LayoutForm",
        amalgamation: "",
        downloadEkhata: "",
        onlineFormatAB: "https://bbmpeaasthi.karnataka.gov.in/office/frmKhathaDownload.aspx",
        fileobjection: "",
        newKhata: "https://bbmp.karnataka.gov.in/newkhata",
        singleSiteApproval: "",
        donotfindMyProperty: "",
    },
    applicationStatus: {
        finalekhataStatusEPID: "",
        neweKhathastatusbasedonePID: "",
        pendingMutation: "",
        searchByPropertyName: "",
    },
    verification: {
        formABVerification: "https://bbmpeaasthi.karnataka.gov.in/office/frmForm3_2Verify.aspx",
        formABView: "https://bbmpeaasthi.karnataka.gov.in/office/frmForm3_2View.aspx?formid=menu",
        ScannedProperty: "",
        propertyRegistered: "https://bbmpeaasthi.karnataka.gov.in/office/frmSearchKaveriProperties.aspx",
        propertyRegisteredUnderKaveri: "https://bbmpeaasthi.karnataka.gov.in/office/frmSearchKaveriProp.aspx",
    },
    reports: {
        reportsDashboard: "https://bbmpeaasthi.karnataka.gov.in/office/PublicReports/frmDashBoardNew.aspx",
        eSwathuDraftReport: "https://bbmpeaasthi.karnataka.gov.in/office/PublicReports/frmDashBoardNew.aspx",
        districtWise: "https://bbmpeaasthi.karnataka.gov.in/office/PublicReports/frmMutationDistrictwise.aspx",
    },
    externalLinks: {
        kaveri: "https://kaveri.karnataka.gov.in/landing-page",
        bhoomi: "https://landrecords.karnataka.gov.in/service2/RTC.aspx",
        easthi: "https://bbmpeaasthi.karnataka.gov.in/",
        propertyTax: "https://bbmptax.karnataka.gov.in/",
        bangloreOne: "https://bbmpeaasthi.karnataka.gov.in/frmBangalore1CentersbyZone.aspx?zone=East",
        processFlow: "https://bbmpeaasthi.karnataka.gov.in/frmProcessFlowDisplay.aspx",
    },
};


export default config;